version: "2.2"

volumes:
  bEP3h4Jy: {}
  bzgp9GzA: {}
  YqMuDvNt: {}
  bUCrHlfC: {}
  K503Vn93: {}
  btZvaPEA: {}
  s4imStra: {}
  Xioaoogm: {}
  RT9eZ8fj: {}

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - bEP3h4Jy:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.8.4
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
    volumes:
      - RT9eZ8fj:/data
      - RT9eZ8fj:/datalog

  coordinator:
    image: apache/druid:32.0.0
    container_name: coordinator
    volumes:
      - s4imStra:/opt/shared
      - K503Vn93:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment

  broker:
    image: apache/druid:32.0.0
    container_name: broker
    volumes:
      - bUCrHlfC:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment

  historical:
    image: apache/druid:32.0.0
    container_name: historical
    volumes:
      - s4imStra:/opt/shared
      - YqMuDvNt:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment

  indexer:
    image: apache/druid:32.0.0
    container_name: indexer
    volumes:
      - s4imStra:/opt/shared
      - bzgp9GzA:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - indexer
    env_file:
      - environment

  router:
    image: apache/druid:32.0.0
    container_name: router
    volumes:
      - btZvaPEA:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - Xioaoogm:/var/lib/kafka/data
    depends_on:
      - zookeeper
      - postgres
      - coordinator
      - broker
      - historical
      - indexer
      - router
